### ISSUE TITLE
custom-cards/surveillance-card

### ISSUE THREAD

**Issue by timdonovanuk** [hacs/default#318]
## Describe why you are flagging this

No longer maintained or working (https://github.com/custom-cards/surveillance-card/issues/20)

**Comment by ludeeus** [comment]
✅  https://github.com/hacs/default/commit/291104f6d2fd6e2e385a47bb0d4484c5b826311c

**Comment by chipriley** [comment]
@ludeeus The maintainer has updated this in the last few days.  Looks like it's no longer stale.  Can we remove from the blacklist? Otherwise, it sits un-upgradable to me as an update in HACS.
