### ISSUE TITLE
atomic7777/atomic_calendar

### ISSUE THREAD

**Issue by marksie1988** [hacs/default#377]
## Describe why you are flagging this
This repository is dead and hasn't been updated, it no longer works with the latest HA.

I have setup a new version here which is being maintained: 
  https://github.com/marksie1988/atomic_calendar_revive

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by maxwroc** [comment]
@marksie1988 I'm on 0.109.1 (latest HA) and atomic_calendar works fine so I don't see a reason for blacklisting it (especially that yours is not available on HACS)

**Comment by marksie1988** [comment]
@maxwroc thats interesting as the reason for moving to the new version was because it stopped working with HA at version 106. 

I created this "revive" version as the current version is no longer developed and there have been no merges of PRs for quite some time. I merged all the PRs and have added more features on top

The reason I supplied the new repo is that this could be added to HACS natively instead of the original which is no longer developed.

**Comment by UbhiTS** [comment]
I just posted a question on the original repo asking the developer if he's still actively maintaining the atomic calendar. Hopefully he or she will answer soon.

**Comment by maxwroc** [comment]
> I'm on HA 109 and the atomic calendar is working perfectly. I'm unable to realy see the difference. I think this would confuse the users which one to install since they are both practically the same.

I second that. @marksie1988  Can you clearly highlight in the README what was added/fixed in your fork (maybe in additional designated section). This way people can easily decide whether thay want to use your card or the original one. 

BTW thanks for taking over this project, I use this card for a long time and wanted to do some UI changes/adjustments so I'm going to add a feature request and maybe send PR some time in the future

**Comment by marksie1988** [comment]
@maxwroc happy to update the readme with the differences. 

Interesting that it works with 109, I'm guessing the issue that was seen in the card was rolled back in the new HA version.

**Comment by ludeeus** [comment]
By the looks of this issue, it sounds like it's still working, so blacklisting it will be overkill.
If that changes I'll be happy to remove it, the author has not done anything on github since september so I doubt that will change now.
But since it's stil working, I'll close this request.
