### ISSUE TITLE
atomic7777/atomic_calendar

### ISSUE THREAD

**Issue by Yllelder** [hacs/default#435]
## Describe why you are flagging this

This component is no longer maintained.

Reference:
https://github.com/atomic7777/atomic_calendar#this-component-is-no-longer-maintained-instead-please-use-this-one---atomic-calendar-revive

**Comment by ludeeus** [comment]
I'm aware, but it still works and the repository is still active (not archived)
I don't see a reason to remove it, it has many users, this was also covered in <https://github.com/hacs/default/issues/377#issuecomment-622295529>
