### ISSUE TITLE
HASL shoud **not** be blacklisted

### ISSUE THREAD

**Issue by DSorlov** [hacs/default#459]
## Describe why you are flagging this

I think HASL have been wrongly blacklisted, probably because of this:
https://github.com/hacs/default/pull/449

**Comment by ludeeus** [comment]
"DSorlov/hasl-platform" was archived, which indicates that the developer is no longer maintaining it.
Archived repositories are removed from HACS.
If you unarchive it, you can make a PR that reverses <https://github.com/hacs/default/commit/e71f92cc728c57e9893510b0bf55675fd0f91c15>
